### ISSUE TITLE
Scope of process(data, {baseUri: baseUri}) 

### ISSUE THREAD

**Issue by nicola** [rdf-ext/rdf-parser-rdfa#3]
This relates to nicola/simplerdf#19

In the RDFaProcessor, the baseUri is extracted from the first parameter used in `process`, I am not sure where it uses the baseUri that we pass in the `options`, any idea on that?

`process(data, {baseUri: baseUri})`

**Comment by bergos** [comment]
It's only used in my [fork of Green Turtle](https://github.com/bergos/green-turtle/blob/master/src/RDFaProcessor.js#L338).

**Comment by nicola** [comment]
Thanks @bergos
